import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "@xyflow/react/dist/style.css";
import "./globals.css";
import Script from "next/script";

const noto = Noto_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto.className} antialiased`}>
        {children}
        <Script src="glsl-optimizer/loader.js" strategy="beforeInteractive" />
        <Script src="glsl-optimizer/glsl-optimizer.js" />
      </body>
    </html>
  );
}
